### ISSUE TITLE
Ошибка "LazyInitializationException: ... no Session" при выгрузке отчета

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#259]
Для брокера ВТБ появляется ошибка.
```
- org.hibernate.LazyInitializationException: could not initialize proxy [ru.investbook.entity.SecurityEntity#RU0007775219] - no Session
at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:170)
at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:310)
at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
at ru.investbook.entity.SecurityEntity$HibernateProxy$H7BZ0iUk.getName(Unknown Source)
at ru.investbook.report.excel.SecuritiesDepositAndWithdrawalExcelTableFactory.create(SecuritiesDepositAndWithdrawalExcelTableFactory.java:53)
at ru.investbook.report.excel.ExcelTableView.createExcelTables(ExcelTableView.java:80)
at ru.investbook.report.excel.ExcelTableView.createExcelTables(ExcelTableView.java:74)
at ru.investbook.report.excel.ExcelView.getExcelTables(ExcelView.java:80)
at ru.investbook.report.excel.ExcelView.lambda$writeTo$0(ExcelView.java:61)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by vananiev** [comment]
По умолчанию `spring.jpa.open-in-view` включен (true), значит объект сессии создается для обрабатывающего потока в начале http запроса и живет до самого конца. Но сборка отчета происходит в несколько потоков (по количеству ядер CPU, gh-180). Executor `ForkJoinPool` может использовать для обработки excel-листа как исходный поток обработчик, так и другой поток. В первом случае проблемы не будет, т.к. объект сессии БД у потока есть. Во втором случае будет ошибка - сессия БД для этого потока никогда не создавалась. Поэтому ошибка "плавающая".

Для исключения ошибки включу для прода настройку `spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true`. Это замедлит для второго случая работу с БД, но гарантирует работоспособность. Многопоточность с этой настройкой будет работать по-прежнему быстрее, чем работа без этой настройки в одном исходном потоке обработчике с имеющейся сессией для БД.
