### ISSUE TITLE
Учет изменений для загрузки отчета Уралсиб Брокера в версии 2023.1

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#524]
Проблема в релиз не уходила, воспроизводится на develop ветке для 2023.1

На java 18 корректно работает
```java
text.matches("(^|(.|\\n)*\\b|(.|\\n)*\\s)" + word + "(\\b(.|\\n)*|\\s(.|\\n)*|$)");
```
На java 19 ошибка "Не обнаружен заголовок таблицы, включающий слова: количество, на начало периода"
```
2023-02-12T23:34:49.246+03:00  WARN 12500 --- [onPool-worker-2] r.i.p.BrokerReportParserServiceImpl      : Произошла ошибка парсинга отчета 'brok_rpt_11043_invest_20220101_20221231_151352_final.xlsx'

java.lang.RuntimeException: Ошибка при парсинге отчета brok_rpt_173_invest_20220101_20221231_151352_final.xlsx
	at org.spacious_team.broker.report_parser.api.InitializableReportTable.initializeIfNeed(InitializableReportTable.java:52) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.InitializableReportTable.getData(InitializableReportTable.java:37) ~[broker-report-parser-api-2022.4.jar:na]
	at ru.investbook.parser.uralsib.PaymentsTable.<init>(PaymentsTable.java:70) ~[classes/:na]
	at ru.investbook.parser.uralsib.CouponAmortizationRedemptionTable.<init>(CouponAmortizationRedemptionTable.java:50) ~[classes/:na]
	at ru.investbook.parser.uralsib.UralsibReportTables.<init>(UralsibReportTables.java:66) ~[classes/:na]
	at ru.investbook.parser.uralsib.UralsibReportTablesFactory.create(UralsibReportTablesFactory.java:43) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.getReportTables(BrokerReportParserServiceImpl.java:177) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport0(BrokerReportParserServiceImpl.java:95) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport(BrokerReportParserServiceImpl.java:63) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.uploadReport(BrokerFileReportController.java:81) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.lambda$uploadBrokerReports$1(BrokerFileReportController.java:70) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: java.lang.RuntimeException: Ошибка при парсинге таблицы 'СОСТОЯНИЕ ПОРТФЕЛЯ ЦЕННЫХ БУМАГ' в отчете brok_rpt_11043_invest_20220101_20221231_151352_final.xlsx
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.parseTable(AbstractReportTable.java:145) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.InitializableReportTable.initializeIfNeed(InitializableReportTable.java:46) ~[broker-report-parser-api-2022.4.jar:na]
	... 23 common frames omitted
Caused by: java.lang.RuntimeException: Не обнаружен заголовок таблицы, включающий слова: количество, на начало периода
	at org.spacious_team.table_wrapper.api.TableColumnImpl.getColumnIndex(TableColumnImpl.java:60) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.TableColumn.getColumnIndex(TableColumn.java:31) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.AbstractTable.getHeaderDescription(AbstractTable.java:112) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.AbstractTable.<init>(AbstractTable.java:72) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.excel.ExcelTable.<init>(ExcelTable.java:42) ~[table-wrapper-excel-impl-2022.7.jar:na]
	at org.spacious_team.table_wrapper.excel.ExcelTableFactory.create(ExcelTableFactory.java:40) ~[table-wrapper-excel-impl-2022.7.jar:na]
	at org.spacious_team.table_wrapper.api.TableFactory.create(TableFactory.java:131) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.ReportPage.create(ReportPage.java:343) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.createTable(AbstractReportTable.java:153) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.parseTable(AbstractReportTable.java:141) ~[broker-report-parser-api-2022.4.jar:na]
	... 24 common frames omitted
```

**Comment by vananiev** [comment]
В java 19 есть несовместимые изменения

**Comment by vananiev** [comment]
Требуется обновиться на table-wrapper-api 2023.1

**Comment by vananiev** [comment]
Требуется обновить table-wrapper-excel-impl и др, т.к. после обновления table-wrapper-api возникает ошибка
```
Caused by: java.lang.IllegalAccessError: class org.spacious_team.table_wrapper.excel.ExcelTableHelper tried to access private method 'void org.spacious_team.table_wrapper.api.TableCellAddress.<init>(int, int)' (org.spacious_team.table_wrapper.excel.ExcelTableHelper and org.spacious_team.table_wrapper.api.TableCellAddress are in unnamed module of loader 'app')
	at org.spacious_team.table_wrapper.excel.ExcelTableHelper.find(ExcelTableHelper.java:73) ~[table-wrapper-excel-impl-2022.7.jar:na]
	at org.spacious_team.table_wrapper.excel.ExcelSheet.find(ExcelSheet.java:45) ~[table-wrapper-excel-impl-2022.7.jar:na]
	at org.spacious_team.table_wrapper.api.ReportPage.find(ReportPage.java:101) ~[table-wrapper-api-c4b923cd72.jar:na]
	at ru.investbook.parser.uralsib.UralsibBrokerReport.checkReportFormat(UralsibBrokerReport.java:82) ~[classes/:na]
	at ru.investbook.parser.uralsib.UralsibBrokerReport.<init>(UralsibBrokerReport.java:74) ~[classes/:na]
	at ru.investbook.parser.uralsib.UralsibBrokerReportFactory.lambda$create$1(UralsibBrokerReportFactory.java:63) ~[classes/:na]
	at org.spacious_team.broker.report_parser.api.AbstractBrokerReportFactory.create(AbstractBrokerReportFactory.java:57) ~[broker-report-parser-api-5faba1a1c3.jar:na]
	at ru.investbook.parser.uralsib.UralsibBrokerReportFactory.create(UralsibBrokerReportFactory.java:65) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.getReportOfUnknownBroker(BrokerReportParserServiceImpl.java:144) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.getBrokerReport(BrokerReportParserServiceImpl.java:133) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport0(BrokerReportParserServiceImpl.java:95) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport(BrokerReportParserServiceImpl.java:64) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.uploadReport(BrokerFileReportController.java:81) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.lambda$uploadBrokerReports$1(BrokerFileReportController.java:70) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at ru.investbook.web.BrokerFileReportController.uploadBrokerReports(BrokerFileReportController.java:69) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.4.jar:6.0.4]
	... 58 common frames omitted
```

**Comment by vananiev** [comment]
Обновления table-wrapper-*-impl завершено. Требуется потестировать.

**Comment by vananiev** [comment]
Восстановлена корректная работа regexp паттерна `\\b` для Тинькофф и ВТБ

**Comment by vananiev** [comment]
Доработана фича #276
