### ISSUE TITLE
Доработать парсер Уралсиб Брокера

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#526]
1. ошибка парсера, если после таблицы "СДЕЛКИ С ФЬЮЧЕРСАМИ И ОПЦИОНАМИ" не встречается таблица "ДВИЖЕНИЕ ДЕНЕЖНЫХ СРЕДСТВ ЗА ОТЧЕТНЫЙ ПЕРИОД" (в примере отчета встречается таблица "ИСПОЛНЕНИЕ КОНТРАКТОВ").
2. В таблице "ДВИЖЕНИЕ ДЕНЕЖНЫХ СРЕДСТВ ЗА ОТЧЕТНЫЙ ПЕРИОД" на сообщении `Перевод ДС на с/с SPBFUT01C23 с с/с SPBFUTI4567. Код клиента 89012. НДС не облагается.` (положение цифр сохранено, но сами цифры изменены) возникает ошибка
```
2023-02-16 23:35:57.071  WARN 6652 --- [  XNIO-1 task-1] o.s.table_wrapper.api.AbstractTable      : Не могу распарсить таблицу 'ДВИЖЕНИЕ ДЕНЕЖНЫХ СРЕДСТВ ЗА ОТЧЕТНЫЙ ПЕРИОД' в brok_rpt_<...>_final.xlsx, строка 2120

java.lang.RuntimeException: Не могу найти код клиента для субсчета SPBFUTI4567
	at ru.investbook.parser.uralsib.CashFlowTable.getClientCode(CashFlowTable.java:109) ~[classes/:na]
	at ru.investbook.parser.uralsib.CashFlowTable.parseRow(CashFlowTable.java:63) ~[classes/:na]
	at ru.investbook.parser.uralsib.CashFlowTable.parseRow(CashFlowTable.java:34) ~[classes/:na]
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.parseRowToCollection(AbstractReportTable.java:168) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.AbstractTable.lambda$getDataCollection$5(AbstractTable.java:146) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.AbstractTable.getDataCollection(AbstractTable.java:160) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.table_wrapper.api.AbstractTable.getDataCollection(AbstractTable.java:145) ~[table-wrapper-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.parseTable(AbstractReportTable.java:164) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.AbstractReportTable.parseTable(AbstractReportTable.java:142) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.InitializableReportTable.initializeIfNeed(InitializableReportTable.java:46) ~[broker-report-parser-api-2022.4.jar:na]
	at org.spacious_team.broker.report_parser.api.InitializableReportTable.getData(InitializableReportTable.java:37) ~[broker-report-parser-api-2022.4.jar:na]
	at ru.investbook.parser.uralsib.UralsibReportTables.getCashFlowTable(UralsibReportTables.java:77) ~[classes/:na]
	at ru.investbook.parser.ReportTablesCachingWrapper.<init>(ReportTablesCachingWrapper.java:51) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.getReportTables(BrokerReportParserServiceImpl.java:178) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport0(BrokerReportParserServiceImpl.java:95) ~[classes/:na]
	at ru.investbook.parser.BrokerReportParserServiceImpl.parseReport(BrokerReportParserServiceImpl.java:63) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.uploadReport(BrokerFileReportController.java:81) ~[classes/:na]
	at ru.investbook.web.BrokerFileReportController.lambda$uploadBrokerReports$1(BrokerFileReportController.java:70) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at ru.investbook.web.BrokerFileReportController.uploadBrokerReports(BrokerFileReportController.java:69) ~[classes/:na]
```
Связано с работой алгоритма, который покрывает кейс gh-236. Нужно доработать.
3.  Настроить загрузку сделок из таблицы "Специальные сделки РЕПО для переноса длинной позиции"
4. Некорректно считается доходность на вкладке "Портфель (RUB)" 
![изображение](https://user-images.githubusercontent.com/11336712/219509300-60bc42ed-f3d3-474b-afb9-99df946906b3.png)
Доподлинно известно, что фин. результат положительный.

**Comment by vananiev** [comment]
3. Усредненная цена покупки или усредненная цена НКД могут быть отрицательными при успешно проведенных сделках. Пример
![изображение](https://user-images.githubusercontent.com/11336712/219508831-05bef057-5877-4229-99b3-c604dd8cc4e3.png)
