### ISSUE TITLE
Символ "/" в номере брокерского счета приводит к ошибке формирования выгрузки

### ISSUE THREAD

**Issue by vananiev** [spacious-team/investbook#91]
При наличии брокерских субсчетов в их наименовании может присутствовать символ "/", который приводит к ошибке при выгрузке отчета
```
java.lang.IllegalArgumentException: Invalid char (/) found at index (15) in sheet name 'Портфель (10212/01) RUB'
at org.apache.poi.ss.util.WorkbookUtil.validateSheetName(WorkbookUtil.java:151)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:873)
at ru.investbook.view.excel.PortfolioStatusExcelTableView.writeTo(PortfolioStatusExcelTableView.java:64)
```

**Comment by vananiev** [comment]
Невалидые в имени листа Excel символы будут заменяться на "-".
